### ISSUE TITLE
Websocket disconnect problem

### ISSUE THREAD

**Issue by kress95** [HackerExperience/HEBorn#133]
A recent PR (PR #131) changed how login and logout works (to make the UI less optimistic), the changes were:

- The game just logs in after socket connection
- The game logs out after socket disconnection

But it looks like that the production connection is too unstable, so the game logs out after 10 seconds of connection.

I'll try to make it more fault tolerant but I really believe that the connection is too unstable, this should be further investigated.

(this problem couldn't be tested locally, local websocket connections are too stable)

**Comment by jasin** [comment]
I think I am seeing this issue here.

I came to report a problem with the 1.hackerexperience.com server logging me back out and back to the login page constantly. As such I have not found a way to stay connected longer than a few seconds. I believe this is the same issue and as such is not fixed!

Jasin

**Comment by PedroHLC** [comment]
Hello @jasin

@kress95 already solved this problem in pr #135, as soon as we all sync this efforts into ours branches this will go up to production (1.hackerexperience.com)
