### ISSUE TITLE
Optmize Jenkins

### ISSUE THREAD

**Issue by PedroHLC** [HackerExperience/HEBorn#139]
Hello @renatomassaro.

Today, each Jenkins builds took almost 3m and 40s to finish.  Sometimes we have to merge more than one PR ready to merge, and because of jenkins after merging one we have to wait before merging the next.

I think we can improve Jenkins in two-ways:

1. Cache npm-modules
  It takes too much time to install modules, and it sometimes it randomly fails.
  We could use a solution like this: [Speeding Up NPM Installs](https://lincolnloop.com/blog/speeding-npm-installs/), saving our tar in $JENKINS_HOME
  (We should also cache, in a separate tar, our submodules...)

2. Change ('Lint', 'Test', 'Compile') from parallel to serial tasks
  We all know how painful is to run multiple instances of elm simultaneously. Poor jenkins farm...
  Lint and tests fails much earlier than compiling would. This would reduce resources usage.

:: OFF-TOPIC:: Is jenkins building PRs for any github member? Can one add a PR with a modified Makefile that will run crazy shell commands?

**Comment by renatomassaro** [comment]
> :: OFF-TOPIC:: Is jenkins building PRs for any github member? Can one add a PR with a modified Makefile that will run crazy shell commands?

It builds automatically only from a whitelist of Github accounts, so someone outside the Github organization would have to be whitelisted first.

> Change ('Lint', 'Test', 'Compile') from parallel to serial tasks

They are serial. I mean, they are parallel with n=1 servers, so effectively they are serial (and in that order, Lint => Test => Compile).

> Cache npm-modules

This is a good option, but the second best one. Checkout phase (which includes npm install) takes ~50s; compilation takes ~1:50m. Caching npm would save us at best 30s (which is great already!), but it would be better if we could cache compilation objects (which could save up to 75s I believe).

Problem is, I tried caching the `elm-stuff` folder but it was always recompiling everything, and I couldn't figure out why. Eventually I forgot it, since it was already fast anyway. Maybe it's time to revisit it. Please take a look at the Jenkinsfile and see if you can spot any obvious fix for this (you can submit tentative fixes and see if the PR build is being cached or not).

If you don't, let me know and we can debug live on the build server.

> we have to wait before merging the next [PR]

You know, that's actually a good thing. Merges into master will result in deliveries to production, so it's a good idea to have some interval between merges. If we merge 2+ PRs and eventually something goes bad on production, we'll have to return to HEAD^2+, and figure out which PR introduced the problem, while if we limit to 1 PR per 30min we are sure which one caused the problem.

Of course, this (potential problems in production) is still not an issue for us, since we can have some downtime (for now), but it's worth getting used to a more "production-like" process & environment. This means (at least):

1) Merges should be deployed at least 30-60 minutes after the previous one, with the exception of important/urgent hot fixes. I don't see it as a potential bottleneck, we just have to plan ourselves ahead. We don't have 1 PR per hour so 1 merge per hour wouldn't be a bottleneck.

2) One person (and only her) should be responsible for merging PRs. This person is responsible for ensuring the PR was rolled out (it could fail during the merge build).

3) Once merged, the PR author(s) must be notified (via a bot on our chatops).

4) The person who merged, and specially the PR author, should keep an eye on our monitors for anything weird. This is helped by 1) real-time metrics on our (yet to be installed) monitor-wall, 2) automatic warning and alerts from bots on our chatops.

4.1) If the change is relatively large, it is a good idea the PR author manually tests the change(s) directly in production.

> Hello @renatomassaro.

Hey. Apparently I take a bottom-up approach for answers :tipping_hand_man:
